version: "3"

tasks:
  migrate:
    aliases:
      - migrate
    desc: "Run local migrations"
    cmds:
      - go run ./cmd/migrator --storage-path=./storage/auth.db --migrations-path=./migrations
  migrate-for-tests:
    aliases:
      - migrate-for-test
    desc: "Run migrations for tests"
    cmds:
      - go run ./cmd/migrator --storage-path=./storage/auth.db --migrations-path=./tests/migrations --migrations-table=migrations_test
  serve:
    aliases:
      - serve
    desc: "Run server"
    cmds:
      - go run ./cmd/auth --config=./config/config.yaml